### ISSUE TITLE
Container tries to pull some content from outside

### ISSUE THREAD

**Issue by pejotes** [treyyoder/quakejs-docker#13]
hello, love the idea of this container to have everything inside. 
Tried to run it, but got this.
``` * Starting Apache httpd web server apache2
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
 *
WARNING: using emscripten GL emulation. This is a collection of limited workarounds, do not expect it to work.
WARNING: using emscripten GL emulation unsafe opts. If weirdness happens, try -s GL_UNSAFE_OPTS=0
ioq3 1.36_GIT_4f7d7bf-2014-02-01 emscripten- Feb 23 2014
----- FS_Startup -----
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect EHOSTUNREACH 104.28.27.218:80
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
```

So it still tries to connect somewhere for assets.

**Comment by readysloth** [comment]
Create a dockerfile like this:

```
FROM treyyoder/quakejs

RUN sed -i '1a\\echo "${SERER} content.quakejs.com" > /etc/hosts' /entrypoint.sh
```
Then run `docker build` and now error should be gone.

**Comment by readysloth** [comment]
@treyyoder

**Comment by treyyoder** [comment]
Updated the image in dockerhub, but if you're building yourself:

`docker build --add-host=content.quakejs.com:127.0.0.1 -t treyyoder/quakejs:latest .`
